import { LegalPage } from "@/components/legal/LegalPage";
import { LEGAL } from "@/lib/legal/config";

export const dynamic = "force-static";
export const metadata = { title: "USC 2257 Compliance Statement | ButterCupp" };

export default function Section2257Page() {
  return (
    <LegalPage title="USC 2257 Compliance Statement">
      <p>
        This statement is provided in accordance with 18 U.S.C. &sect; 2257
        and 28 C.F.R. Part 75. It applies to visual depictions of actual
        human beings engaged in sexually explicit conduct that may appear on
        ButterCupp.
      </p>

      <h2>1. AI-generated imagery</h2>
      <p>
        The vast majority of imagery on ButterCupp is generated by artificial
        intelligence and does not depict actual human beings. Purely
        AI-generated visual depictions are not subject to the record-keeping
        requirements of 18 U.S.C. &sect; 2257, because no real person is
        performing. Where a companion has a stated in-fiction age, that age
        is enforced by the platform to be 18 or older at creation time.
      </p>

      <h2>2. Real-person imagery is not permitted</h2>
      <p>
        ButterCupp prohibits users from uploading, generating, or requesting
        sexually explicit depictions of real, identifiable people. See our{" "}
        <a href="/legal/content-policy" target="_blank" rel="noopener noreferrer">
          Content and Community Policy
        </a>{" "}
        for the full list of prohibited categories.
      </p>

      <h2>3. Custodian of records</h2>
      <p>
        To the extent any depiction of an actual human performer appears on
        the platform, the custodian of records is:
      </p>
      <p>
        <strong>{LEGAL.COMPANY}</strong>
        <br />
        Custodian of Records
        <br />
        {LEGAL.JURISDICTION}
        <br />
        <a href={`mailto:${LEGAL.CONTACT_EMAIL}`}>{LEGAL.CONTACT_EMAIL}</a>
      </p>

      <h2>4. Age verification</h2>
      <p>
        All ButterCupp users must be at least 18 years old and complete an
        age-verification step at signup. In jurisdictions that require
        third-party age assurance, we use an accredited vendor.
      </p>
    </LegalPage>
  );
}
