// kohya SDXL LoRA trainer config builder and training runner.
//
// Responsibilities:
//   1. buildKohyaConfig: produce a TOML training config for kohya_ss SDXL LoRA
//      training (rank=<rank>, alpha=16, resolution=1024x1024).
//   2. runTraining: orchestrate a training job via injected box deps
//      (submitJob, collectCheckpoints). No real SSH/HTTP here; box wiring
//      is deferred to Task 13/infra.
//
// All box interaction is injected through TrainingDeps so this module is
// fully unit-testable without a live training box.

/** Args for building the kohya SDXL TOML config. */
export interface BuildKohyaConfigArgs {
  /** Absolute path to the prepared dataset directory on the training box. */
  datasetDir: string;
  /** Output name for the LoRA checkpoint files (e.g. "ch_abc123"). */
  outputName: string;
  /** LoRA network rank (network_dim). Alpha is fixed at 16. */
  rank: number;
}

/**
 * Build a kohya_ss SDXL LoRA training config in TOML format.
 *
 * Fixed settings:
 *   - network_alpha = 16
 *   - resolution = 1024 x 1024
 *   - mixed_precision = "bf16"
 *   - max_train_steps = 1500
 *   - save_every_n_steps = 500
 *   - network_module = "networks.lora"
 *   - enable_bucket = true (dynamic aspect-ratio bucketing)
 *
 * The caller supplies rank, datasetDir, and outputName.
 */
export function buildKohyaConfig(args: BuildKohyaConfigArgs): string {
  const { datasetDir, outputName, rank } = args;

  const lines: string[] = [
    "# kohya_ss SDXL LoRA training config",
    "# Generated by train.ts; do not edit by hand.",
    "",
    "[general]",
    `enable_bucket = true`,
    "",
    "[model]",
    `pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"`,
    `mixed_precision = "bf16"`,
    "",
    "[dataset]",
    `train_data_dir = "${datasetDir}"`,
    `resolution = "1024,1024"`,
    "",
    "[output]",
    `output_name = "${outputName}"`,
    `output_dir = "${datasetDir}/output"`,
    `save_every_n_steps = 500`,
    `save_model_as = "safetensors"`,
    "",
    "[training]",
    `max_train_steps = 1500`,
    `learning_rate = 1e-4`,
    `unet_lr = 1e-4`,
    `text_encoder_lr = 5e-5`,
    `lr_scheduler = "cosine_with_restarts"`,
    `lr_warmup_steps = 100`,
    `train_batch_size = 1`,
    `gradient_accumulation_steps = 1`,
    `gradient_checkpointing = true`,
    `mixed_precision = "bf16"`,
    `seed = 42`,
    "",
    "[network]",
    `network_module = "networks.lora"`,
    `network_dim = ${rank}`,
    `network_alpha = 16`,
  ];

  return lines.join("\n") + "\n";
}

/** A single checkpoint produced by the training run. */
export interface Checkpoint {
  /** Training step at which this checkpoint was saved. */
  step: number;
  /** S3 key for the checkpoint artifact. */
  key: string;
}

/** Result returned by runTraining. */
export interface TrainingResult {
  checkpoints: Checkpoint[];
}

/**
 * Dependency injection bag for training box interaction.
 * Swap real impls for fakes in tests.
 */
export interface TrainingDeps {
  /**
   * Submit the training job to the ephemeral box.
   * Receives the full TOML config string.
   * Returns a jobId the box uses to track the run.
   */
  submitJob(config: string): Promise<string>;
  /**
   * Collect checkpoint artifacts once the job is done.
   * Returns an array of (step, S3-key) pairs in step order.
   */
  collectCheckpoints(jobId: string): Promise<Checkpoint[]>;
}

/**
 * Run a kohya SDXL LoRA training job on the ephemeral training box.
 *
 * Flow:
 *   1. Build the TOML config via buildKohyaConfig.
 *   2. Submit the job via deps.submitJob (returns a jobId).
 *   3. Collect checkpoints via deps.collectCheckpoints(jobId).
 *   4. Return the checkpoints.
 *
 * Real box wiring (SSH tunnel, HTTP API) is not here by design.
 * Task 13 wires the production Deps implementation.
 */
export async function runTraining(
  args: BuildKohyaConfigArgs,
  deps: TrainingDeps,
): Promise<TrainingResult> {
  const config = buildKohyaConfig(args);
  const jobId = await deps.submitJob(config);
  const checkpoints = await deps.collectCheckpoints(jobId);
  return { checkpoints };
}
