import { LegalPage } from "@/components/legal/LegalPage";
import { LEGAL } from "@/lib/legal/config";

export const dynamic = "force-static";
export const metadata = { title: "Terms of Service | Poppy" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <p>
        These Terms of Service (the &ldquo;Terms&rdquo;) govern your access to
        and use of the Poppy platform operated by {LEGAL.COMPANY}
        (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an account or using
        the service you agree to these Terms.
      </p>

      <h2>1. Acceptance</h2>
      <p>
        By clicking &ldquo;Create account&rdquo;, checking the acceptance
        boxes at sign-up, or otherwise using Poppy, you accept these Terms
        and our{" "}
        <a href="/legal/privacy" target="_blank" rel="noopener noreferrer">
          Privacy Policy
        </a>
        . If you do not accept, do not use the service.
      </p>

      <h2>2. Eligibility (18+)</h2>
      <p>
        Poppy is a mature-content platform limited to users who are at least
        18 years old and who are of the age of majority in {LEGAL.JURISDICTION}
        and in their local jurisdiction. You confirm your date of birth and
        jurisdiction during signup and during the age-gate flow. Providing a
        false date of birth is a material breach of these Terms.
      </p>

      <h2>3. Your account</h2>
      <p>
        You are responsible for the security of your credentials and every
        action taken under your account. Notify us at {LEGAL.CONTACT_EMAIL}
        if you suspect unauthorized use.
      </p>

      <h2>4. Acceptable use</h2>
      <p>
        You will comply with our{" "}
        <a href="/legal/content-policy" target="_blank" rel="noopener noreferrer">
          Content and Community Policy
        </a>
        . You will not attempt to generate content depicting minors,
        non-consensual acts, real identifiable people without consent, or any
        other prohibited category described in that policy.
      </p>

      <h2>5. AI-generated content and California SB 243 disclosure</h2>
      <p>
        Poppy characters are software. Every message, voice note, and image
        is generated by an artificial intelligence system in response to your
        prompts. Companions do not have feelings, memory outside the product,
        or knowledge of the real world beyond what you tell them. Per
        California Senate Bill 243, we display a persistent AI disclosure
        inside the app and route certain crisis signals to human-safety
        resources. Do not rely on Poppy for medical, legal, financial, or
        emergency advice.
      </p>

      <h2>6. Subscriptions and duration passes</h2>
      <p>
        Poppy offers time-boxed access via Daily, Weekly, and Monthly passes
        purchased through third-party mature-friendly processors. Passes are
        non-refundable except as described in our{" "}
        <a href="/legal/refund" target="_blank" rel="noopener noreferrer">
          Refund Policy
        </a>
        .
      </p>

      <h2>7. Termination</h2>
      <p>
        We may suspend or terminate your account for breach of these Terms or
        our Content Policy. You may terminate at any time from the Settings
        page.
      </p>

      <h2>8. Disclaimers and limitation of liability</h2>
      <p>
        Poppy is provided &ldquo;as is&rdquo; without warranty of any kind.
        To the maximum extent permitted by law, {LEGAL.COMPANY} disclaims all
        implied warranties and is not liable for indirect or consequential
        damages arising from your use of the service.
      </p>

      <h2>9. Governing law</h2>
      <p>
        These Terms are governed by the laws of {LEGAL.JURISDICTION} without
        regard to conflict-of-laws principles.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions: <a href={`mailto:${LEGAL.CONTACT_EMAIL}`}>{LEGAL.CONTACT_EMAIL}</a>.
      </p>
    </LegalPage>
  );
}
